// English → Spanish translations in BIP format
// Format: numeric key with translations separated by pipe (|)
// English is the primary key side

const englishDictionary = {
  // Common greetings and polite expressions
  "1": "hello|hola",
  "2": "goodbye|adiós",
  "3": "please|por favor",
  "4": "thank you|gracias",
  "5": "thanks|gracias",
  "6": "yes|sí",
  "7": "no|no",
  "8": "excuse me|disculpe",
  "9": "sorry|lo siento",

  // Family and people
  "10": "friend|amigo",
  "11": "family|familia",
  "12": "mother|madre",
  "13": "father|padre",
  "14": "sister|hermana",
  "15": "brother|hermano",
  "16": "son|hijo",
  "17": "daughter|hija",
  "18": "man|hombre",
  "19": "woman|mujer",
  "20": "child|niño",
  "21": "girl|niña",
  "22": "boy|niño",

  // Food and drink
  "23": "water|agua",
  "24": "food|comida",
  "25": "bread|pan",
  "26": "meat|carne",
  "27": "fish|pescado",
  "28": "chicken|pollo",
  "29": "rice|arroz",
  "30": "beans|frijoles",
  "31": "cheese|queso",
  "32": "milk|leche",
  "33": "coffee|café",
  "34": "tea|té",
  "35": "wine|vino",
  "36": "beer|cerveza",
  "37": "juice|jugo",
  "38": "apple|manzana",
  "39": "banana|plátano",
  "40": "orange|naranja",
  "41": "strawberry|fresa",
  "42": "grape|uva",
  "43": "potato|papa",
  "44": "tomato|tomate",
  "45": "onion|cebolla",

  // Animals
  "46": "dog|perro",
  "47": "cat|gato",
  "48": "bird|pájaro",
  "49": "fish|pez",
  "50": "horse|caballo",
  "51": "cow|vaca",
  "52": "pig|cerdo",
  "53": "sheep|oveja",
  "54": "chicken|gallina",
  "55": "duck|pato",
  "56": "rabbit|conejo",
  "57": "lion|león",
  "58": "tiger|tigre",
  "59": "bear|oso",
  "60": "elephant|elefante",
  "61": "monkey|mono",
  "62": "snake|serpiente",
  "63": "spider|araña",
  "64": "ant|hormiga",
  "65": "bee|abeja",

  // Nature
  "66": "tree|árbol",
  "67": "flower|flor",
  "68": "grass|hierba",
  "69": "sun|sol",
  "70": "moon|luna",
  "71": "star|estrella",
  "72": "sky|cielo",
  "73": "cloud|nube",
  "74": "rain|lluvia",
  "75": "snow|nieve",
  "76": "wind|viento",
  "77": "storm|tormenta",
  "78": "ocean|océano",
  "79": "sea|mar",
  "80": "river|río",
  "81": "mountain|montaña",
  "82": "valley|valle",
  "83": "desert|desierto",
  "84": "forest|bosque",
  "85": "beach|playa",

  // House and home
  "86": "house|casa",
  "87": "home|hogar",
  "88": "room|habitación",
  "89": "bedroom|dormitorio",
  "90": "kitchen|cocina",
  "91": "bathroom|baño",
  "92": "living room|sala de estar",
  "93": "door|puerta",
  "94": "window|ventana",
  "95": "wall|pared",
  "96": "roof|techo",
  "97": "floor|suelo",
  "98": "bed|cama",
  "99": "table|mesa",
  "100": "chair|silla",
  "101": "sofa|sofá",
  "102": "desk|escritorio",
  "103": "lamp|lámpara",
  "104": "picture|cuadro",

  // Clothing
  "105": "shirt|camisa",
  "106": "pants|pantalones",
  "107": "skirt|falda",
  "108": "dress|vestido",
  "109": "jacket|chaqueta",
  "110": "coat|abrigo",
  "111": "shoe|zapato",
  "112": "boot|bota",
  "113": "hat|sombrero",
  "114": "glove|guante",
  "115": "sock|calcetín",
  "116": "underwear|ropa interior",
  "117": "tie|corbata",
  "118": "scarf|bufanda",
  "119": "belt|cinturón",

  // Time
  "120": "time|tiempo",
  "121": "day|día",
  "122": "night|noche",
  "123": "morning|mañana",
  "124": "afternoon|tarde",
  "125": "evening|noche",
  "126": "week|semana",
  "127": "month|mes",
  "128": "year|año",
  "129": "hour|hora",
  "130": "minute|minuto",
  "131": "second|segundo",

  // Days of the week
  "132": "monday|lunes",
  "133": "tuesday|martes",
  "134": "wednesday|miércoles",
  "135": "thursday|jueves",
  "136": "friday|viernes",
  "137": "saturday|sábado",
  "138": "sunday|domingo",

  // Months
  "139": "january|enero",
  "140": "february|febrero",
  "141": "march|marzo",
  "142": "april|abril",
  "143": "may|mayo",
  "144": "june|junio",
  "145": "july|julio",
  "146": "august|agosto",
  "147": "september|septiembre",
  "148": "october|octubre",
  "149": "november|noviembre",
  "150": "december|diciembre",

  // Colors
  "151": "red|rojo",
  "152": "blue|azul",
  "153": "green|verde",
  "154": "yellow|amarillo",
  "155": "orange|naranja",
  "156": "purple|púrpura",
  "157": "pink|rosa",
  "158": "brown|marrón",
  "159": "black|negro",
  "160": "white|blanco",
  "161": "gray|gris",
  "162": "grey|gris",

  // Common verbs
  "163": "to be|ser",
  "164": "to have|tener",
  "165": "to do|hacer",
  "166": "to go|ir",
  "167": "to come|venir",
  "168": "to see|ver",
  "169": "to hear|oír",
  "170": "to speak|hablar",
  "171": "to eat|comer",
  "172": "to drink|beber",
  "173": "to sleep|dormir",
  "174": "to wake|despertar",
  "175": "to work|trabajar",
  "176": "to play|jugar",
  "177": "to learn|aprender",
  "178": "to read|leer",
  "179": "to write|escribir",
  "180": "to think|pensar",
  "181": "to know|saber",
  "182": "to understand|entender",
  "183": "to want|querer",
  "184": "to need|necesitar",
  "185": "to like|gustar",
  "186": "to love|amar",
  "187": "to hate|odiar",
  "188": "to help|ayudar",
  "189": "to give|dar",
  "190": "to take|tomar",
  "191": "to walk|caminar",
  "192": "to run|correr",
  "193": "to jump|saltar",
  "194": "to dance|bailar",
  "195": "to sing|cantar",
  "196": "to laugh|reír",
  "197": "to cry|llorar",
  "198": "to smile|sonreír",

  // Adjectives
  "199": "big|grande",
  "200": "small|pequeño",
  "201": "tall|alto",
  "202": "short|corto",
  "203": "long|largo",
  "204": "good|bueno",
  "205": "bad|malo",
  "206": "hot|caliente",
  "207": "cold|frío",
  "208": "warm|cálido",
  "209": "cool|fresco",
  "210": "wet|mojado",
  "211": "dry|seco",
  "212": "clean|limpio",
  "213": "dirty|sucio",
  "214": "happy|feliz",
  "215": "sad|triste",
  "216": "angry|enojado",
  "217": "calm|tranquilo",
  "218": "fast|rápido",
  "219": "slow|lento",
  "220": "easy|fácil",
  "221": "hard|difícil",
  "222": "young|joven",
  "223": "old|viejo",
  "224": "new|nuevo",
  "225": "beautiful|hermoso",
  "226": "ugly|feo",
  "227": "strong|fuerte",
  "228": "weak|débil",
  "229": "rich|rico",
  "230": "poor|pobre",
  "231": "expensive|caro",
  "232": "cheap|barato",
  "233": "heavy|pesado",
  "234": "light|ligero",
  "1812": "tiny|pequeño",
  "1813": "tip|consejo",
  "1814": "tired|cansado",

  // Common phrases
  "238": "good morning|buenos días",
  "239": "good afternoon|buenas tardes",
  "240": "good evening|buenas noches",
  "241": "good night|buenas noches",
  "242": "how are you|cómo estás",
  "243": "nice to meet you|mucho gusto",
  "244": "what is your name|cuál es tu nombre",
  "245": "my name is|mi nombre es",
  "246": "do you speak english|hablas inglés",
  "247": "i love you|te amo",
  "248": "congratulations|felicitaciones",
  "249": "happy birthday|feliz cumpleaños",
  "250": "merry christmas|feliz navidad",
  "251": "happy new year|feliz año nuevo"
};

module.exports = englishDictionary;
