// Proverbs Seed — 18 proverbs per language
// Languages: English, Spanish, French, Dutch, German, Portuguese

const proverbs = [
  // ─── ENGLISH ───────────────────────────────────────────────────────────────
  {
    language: "English",
    code: "en",
    text: "Actions speak louder than words.",
    meaning: "What you do matters more than what you say.",
  },
  {
    language: "English",
    code: "en",
    text: "All that glitters is not gold.",
    meaning: "Appearances can be deceiving.",
  },
  {
    language: "English",
    code: "en",
    text: "A stitch in time saves nine.",
    meaning: "Fixing a problem early prevents bigger problems later.",
  },
  {
    language: "English",
    code: "en",
    text: "Better late than never.",
    meaning: "It is better to do something late than not at all.",
  },
  {
    language: "English",
    code: "en",
    text: "Birds of a feather flock together.",
    meaning: "People with similar interests tend to associate with each other.",
  },
  {
    language: "English",
    code: "en",
    text: "Don't judge a book by its cover.",
    meaning: "Don't form opinions based on appearances alone.",
  },
  {
    language: "English",
    code: "en",
    text: "Every cloud has a silver lining.",
    meaning: "Every difficult situation has a positive aspect.",
  },
  {
    language: "English",
    code: "en",
    text: "The early bird catches the worm.",
    meaning: "Those who start early have an advantage.",
  },
  {
    language: "English",
    code: "en",
    text: "Too many cooks spoil the broth.",
    meaning: "Too many people involved in something can ruin it.",
  },
  {
    language: "English",
    code: "en",
    text: "When in Rome, do as the Romans do.",
    meaning: "Adapt to the customs of the place you are visiting.",
  },
  {
    language: "English",
    code: "en",
    text: "Two heads are better than one.",
    meaning: "Collaboration leads to better results.",
  },
  {
    language: "English",
    code: "en",
    text: "The grass is always greener on the other side.",
    meaning: "Other people's situations always seem better than your own.",
  },
  {
    language: "English",
    code: "en",
    text: "You reap what you sow.",
    meaning: "Your actions have consequences.",
  },
  {
    language: "English",
    code: "en",
    text: "Practice makes perfect.",
    meaning: "Repeating something makes you better at it.",
  },
  {
    language: "English",
    code: "en",
    text: "Don't bite the hand that feeds you.",
    meaning: "Don't harm those who help you.",
  },
  {
    language: "English",
    code: "en",
    text: "Absence makes the heart grow fonder.",
    meaning: "We appreciate things more when they are away.",
  },
  {
    language: "English",
    code: "en",
    text: "A fool and his money are soon parted.",
    meaning: "Foolish people spend money recklessly.",
  },
  {
    language: "English",
    code: "en",
    text: "Fortune favors the bold.",
    meaning: "Courageous people are more likely to succeed.",
  },

  // ─── SPANISH ───────────────────────────────────────────────────────────────
  {
    language: "Spanish",
    code: "es",
    text: "Camarón que se duerme, se lo lleva la corriente.",
    meaning: "Those who are not alert will be swept away by events.",
  },
  {
    language: "Spanish",
    code: "es",
    text: "No hay mal que por bien no venga.",
    meaning: "Every bad situation has some good in it.",
  },
  {
    language: "Spanish",
    code: "es",
    text: "A caballo regalado no le mires el diente.",
    meaning: "Don't find fault with a gift.",
  },
  {
    language: "Spanish",
    code: "es",
    text: "Dime con quién andas y te diré quién eres.",
    meaning: "You are judged by the company you keep.",
  },
  {
    language: "Spanish",
    code: "es",
    text: "El que mucho abarca, poco aprieta.",
    meaning: "Those who try to do too much accomplish little.",
  },
  {
    language: "Spanish",
    code: "es",
    text: "Más vale tarde que nunca.",
    meaning: "Better late than never.",
  },
  {
    language: "Spanish",
    code: "es",
    text: "En boca cerrada no entran moscas.",
    meaning: "Keeping silent avoids trouble.",
  },
  {
    language: "Spanish",
    code: "es",
    text: "Ojos que no ven, corazón que no siente.",
    meaning: "What you don't know doesn't hurt you.",
  },
  {
    language: "Spanish",
    code: "es",
    text: "Al mal tiempo, buena cara.",
    meaning: "Face adversity with a positive attitude.",
  },
  {
    language: "Spanish",
    code: "es",
    text: "No por mucho madrugar amanece más temprano.",
    meaning: "Rushing things doesn't make them happen sooner.",
  },
  {
    language: "Spanish",
    code: "es",
    text: "Quien siembra vientos, recoge tempestades.",
    meaning: "If you cause trouble, expect trouble in return.",
  },
  {
    language: "Spanish",
    code: "es",
    text: "A lo hecho, pecho.",
    meaning: "Face the consequences of your actions bravely.",
  },
  {
    language: "Spanish",
    code: "es",
    text: "Más vale pájaro en mano que ciento volando.",
    meaning: "A sure thing is better than uncertain possibilities.",
  },
  {
    language: "Spanish",
    code: "es",
    text: "Cada oveja con su pareja.",
    meaning: "Like goes with like.",
  },
  {
    language: "Spanish",
    code: "es",
    text: "El hábito no hace al monje.",
    meaning: "Clothes don't make the person.",
  },
  {
    language: "Spanish",
    code: "es",
    text: "Donde hay humo, hay fuego.",
    meaning: "Where there's smoke, there's fire.",
  },
  {
    language: "Spanish",
    code: "es",
    text: "Agua que no has de beber, déjala correr.",
    meaning: "Don't interfere in things that don't concern you.",
  },
  {
    language: "Spanish",
    code: "es",
    text: "No hay peor ciego que el que no quiere ver.",
    meaning: "The worst kind of ignorance is willful ignorance.",
  },

  // ─── FRENCH ────────────────────────────────────────────────────────────────
  {
    language: "French",
    code: "fr",
    text: "Petit à petit, l'oiseau fait son nid.",
    meaning: "Little by little, great things are accomplished.",
  },
  {
    language: "French",
    code: "fr",
    text: "Mieux vaut tard que jamais.",
    meaning: "Better late than never.",
  },
  {
    language: "French",
    code: "fr",
    text: "Les absents ont toujours tort.",
    meaning: "Those who are absent are always blamed.",
  },
  {
    language: "French",
    code: "fr",
    text: "Après la pluie, le beau temps.",
    meaning: "After hardship comes happiness.",
  },
  {
    language: "French",
    code: "fr",
    text: "Quand le chat n'est pas là, les souris dansent.",
    meaning: "When the cat is away, the mice will play.",
  },
  {
    language: "French",
    code: "fr",
    text: "Il ne faut pas vendre la peau de l'ours avant de l'avoir tué.",
    meaning: "Don't count your chickens before they hatch.",
  },
  {
    language: "French",
    code: "fr",
    text: "L'habit ne fait pas le moine.",
    meaning: "Clothes don't make the person.",
  },
  {
    language: "French",
    code: "fr",
    text: "Qui ne risque rien n'a rien.",
    meaning: "Nothing ventured, nothing gained.",
  },
  {
    language: "French",
    code: "fr",
    text: "Les cordonniers sont les plus mal chaussés.",
    meaning: "Experts often neglect applying their own expertise to themselves.",
  },
  {
    language: "French",
    code: "fr",
    text: "On n'apprend pas à un vieux singe à faire des grimaces.",
    meaning: "You can't teach an old dog new tricks.",
  },
  {
    language: "French",
    code: "fr",
    text: "Vouloir, c'est pouvoir.",
    meaning: "Where there's a will, there's a way.",
  },
  {
    language: "French",
    code: "fr",
    text: "Dis-moi qui tu hantes, je te dirai qui tu es.",
    meaning: "You are known by the company you keep.",
  },
  {
    language: "French",
    code: "fr",
    text: "Il faut battre le fer pendant qu'il est chaud.",
    meaning: "Strike while the iron is hot.",
  },
  {
    language: "French",
    code: "fr",
    text: "Mieux vaut prévenir que guérir.",
    meaning: "Prevention is better than cure.",
  },
  {
    language: "French",
    code: "fr",
    text: "La nuit, tous les chats sont gris.",
    meaning: "In the dark, all distinctions disappear.",
  },
  {
    language: "French",
    code: "fr",
    text: "À quelque chose, malheur est bon.",
    meaning: "Every cloud has a silver lining.",
  },
  {
    language: "French",
    code: "fr",
    text: "Pierre qui roule n'amasse pas mousse.",
    meaning: "A rolling stone gathers no moss.",
  },
  {
    language: "French",
    code: "fr",
    text: "Les loups ne se mangent pas entre eux.",
    meaning: "People of the same kind protect each other.",
  },

  // ─── DUTCH ─────────────────────────────────────────────────────────────────
  {
    language: "Dutch",
    code: "nl",
    text: "De aanhouder wint.",
    meaning: "Persistence leads to success.",
  },
  {
    language: "Dutch",
    code: "nl",
    text: "Al draagt een aap een gouden ring, het is en blijft een lelijk ding.",
    meaning: "Fine clothes don't hide a bad character.",
  },
  {
    language: "Dutch",
    code: "nl",
    text: "Wie het kleine niet eert, is het grote niet weerd.",
    meaning: "If you can't appreciate small things, you don't deserve big ones.",
  },
  {
    language: "Dutch",
    code: "nl",
    text: "Oost, west, thuis best.",
    meaning: "East, west, home is best.",
  },
  {
    language: "Dutch",
    code: "nl",
    text: "Zoals het klokje thuis tikt, tikt het nergens.",
    meaning: "There's no place like home.",
  },
  {
    language: "Dutch",
    code: "nl",
    text: "Leugens hebben korte benen.",
    meaning: "Lies don't last long.",
  },
  {
    language: "Dutch",
    code: "nl",
    text: "Nieuwe bezems vegen schoon.",
    meaning: "New brooms sweep clean — new leaders bring change.",
  },
  {
    language: "Dutch",
    code: "nl",
    text: "Beter één vogel in de hand dan tien in de lucht.",
    meaning: "A bird in the hand is worth two in the bush.",
  },
  {
    language: "Dutch",
    code: "nl",
    text: "De pot verwijt de ketel dat hij zwart ziet.",
    meaning: "The pot calling the kettle black.",
  },
  {
    language: "Dutch",
    code: "nl",
    text: "Wees geen watje.",
    meaning: "Don't be a pushover — be strong.",
  },
  {
    language: "Dutch",
    code: "nl",
    text: "Hoe meer zielen, hoe meer vreugd.",
    meaning: "The more the merrier.",
  },
  {
    language: "Dutch",
    code: "nl",
    text: "Met de hoed in de hand kom je door het ganse land.",
    meaning: "Politeness and humility will take you far.",
  },
  {
    language: "Dutch",
    code: "nl",
    text: "Goed begonnen is half gewonnen.",
    meaning: "Well begun is half done.",
  },
  {
    language: "Dutch",
    code: "nl",
    text: "Na regen komt zonneschijn.",
    meaning: "After rain comes sunshine — better times follow hard times.",
  },
  {
    language: "Dutch",
    code: "nl",
    text: "Al is de leugen nog zo snel, de waarheid achterhaalt haar wel.",
    meaning: "Truth will always catch up with lies.",
  },
  {
    language: "Dutch",
    code: "nl",
    text: "Bezint eer ge begint.",
    meaning: "Think before you act.",
  },
  {
    language: "Dutch",
    code: "nl",
    text: "Tijd is geld.",
    meaning: "Time is money.",
  },
  {
    language: "Dutch",
    code: "nl",
    text: "Elk huisje heeft zijn kruisje.",
    meaning: "Every household has its troubles.",
  },

  // ─── GERMAN ────────────────────────────────────────────────────────────────
  {
    language: "German",
    code: "de",
    text: "Morgenstund hat Gold im Mund.",
    meaning: "The early bird catches the worm.",
  },
  {
    language: "German",
    code: "de",
    text: "Übung macht den Meister.",
    meaning: "Practice makes perfect.",
  },
  {
    language: "German",
    code: "de",
    text: "Was du heute kannst besorgen, das verschiebe nicht auf morgen.",
    meaning: "Don't put off until tomorrow what you can do today.",
  },
  {
    language: "German",
    code: "de",
    text: "Aller Anfang ist schwer.",
    meaning: "Every beginning is difficult.",
  },
  {
    language: "German",
    code: "de",
    text: "Der Apfel fällt nicht weit vom Stamm.",
    meaning: "The apple doesn't fall far from the tree.",
  },
  {
    language: "German",
    code: "de",
    text: "Wer zuletzt lacht, lacht am besten.",
    meaning: "He who laughs last, laughs best.",
  },
  {
    language: "German",
    code: "de",
    text: "Kleider machen Leute.",
    meaning: "Clothes make the man.",
  },
  {
    language: "German",
    code: "de",
    text: "Lügen haben kurze Beine.",
    meaning: "Lies don't get you very far.",
  },
  {
    language: "German",
    code: "de",
    text: "Ende gut, alles gut.",
    meaning: "All's well that ends well.",
  },
  {
    language: "German",
    code: "de",
    text: "Man soll den Tag nicht vor dem Abend loben.",
    meaning: "Don't count your chickens before they hatch.",
  },
  {
    language: "German",
    code: "de",
    text: "Viele Köche verderben den Brei.",
    meaning: "Too many cooks spoil the broth.",
  },
  {
    language: "German",
    code: "de",
    text: "Stille Wasser sind tief.",
    meaning: "Still waters run deep.",
  },
  {
    language: "German",
    code: "de",
    text: "Wer andern eine Grube gräbt, fällt selbst hinein.",
    meaning: "Those who set traps for others fall into them themselves.",
  },
  {
    language: "German",
    code: "de",
    text: "Ohne Fleiß kein Preis.",
    meaning: "No pain, no gain.",
  },
  {
    language: "German",
    code: "de",
    text: "Der frühe Vogel fängt den Wurm.",
    meaning: "The early bird catches the worm.",
  },
  {
    language: "German",
    code: "de",
    text: "Mit Speck fängt man Mäuse.",
    meaning: "You catch more flies with honey than with vinegar.",
  },
  {
    language: "German",
    code: "de",
    text: "Reden ist Silber, Schweigen ist Gold.",
    meaning: "Speech is silver, silence is golden.",
  },
  {
    language: "German",
    code: "de",
    text: "Durch Schaden wird man klug.",
    meaning: "One learns from one's mistakes.",
  },

  // ─── PORTUGUESE ────────────────────────────────────────────────────────────
  {
    language: "Portuguese",
    code: "pt",
    text: "Devagar se vai ao longe.",
    meaning: "Slowly but surely you get there.",
  },
  {
    language: "Portuguese",
    code: "pt",
    text: "Quem não arrisca, não petisca.",
    meaning: "Nothing ventured, nothing gained.",
  },
  {
    language: "Portuguese",
    code: "pt",
    text: "Água mole em pedra dura, tanto bate até que fura.",
    meaning: "Persistent effort can overcome great obstacles.",
  },
  {
    language: "Portuguese",
    code: "pt",
    text: "Em casa de ferreiro, espeto de pau.",
    meaning: "The shoemaker's children go barefoot.",
  },
  {
    language: "Portuguese",
    code: "pt",
    text: "Não adianta chorar sobre o leite derramado.",
    meaning: "No use crying over spilled milk.",
  },
  {
    language: "Portuguese",
    code: "pt",
    text: "Quem com ferro fere, com ferro será ferido.",
    meaning: "Those who live by the sword die by the sword.",
  },
  {
    language: "Portuguese",
    code: "pt",
    text: "Deus ajuda quem cedo madruga.",
    meaning: "God helps those who help themselves.",
  },
  {
    language: "Portuguese",
    code: "pt",
    text: "A mentira tem pernas curtas.",
    meaning: "Lies don't last long.",
  },
  {
    language: "Portuguese",
    code: "pt",
    text: "Mais vale um pássaro na mão do que dois a voar.",
    meaning: "A bird in the hand is worth two in the bush.",
  },
  {
    language: "Portuguese",
    code: "pt",
    text: "Cada macaco no seu galho.",
    meaning: "Stick to what you know best.",
  },
  {
    language: "Portuguese",
    code: "pt",
    text: "Quem semeia ventos colhe tempestades.",
    meaning: "Those who sow the wind reap the whirlwind.",
  },
  {
    language: "Portuguese",
    code: "pt",
    text: "O hábito não faz o monge.",
    meaning: "Clothes don't make the person.",
  },
  {
    language: "Portuguese",
    code: "pt",
    text: "Dize-me com quem andas e dir-te-ei quem és.",
    meaning: "You are known by the company you keep.",
  },
  {
    language: "Portuguese",
    code: "pt",
    text: "Antes tarde do que nunca.",
    meaning: "Better late than never.",
  },
  {
    language: "Portuguese",
    code: "pt",
    text: "Não há bela sem senão.",
    meaning: "Every rose has its thorn.",
  },
  {
    language: "Portuguese",
    code: "pt",
    text: "Quem tudo quer, tudo perde.",
    meaning: "Those who want everything end up with nothing.",
  },
  {
    language: "Portuguese",
    code: "pt",
    text: "O pior cego é o que não quer ver.",
    meaning: "The worst blind person is one who refuses to see.",
  },
  {
    language: "Portuguese",
    code: "pt",
    text: "Filho de peixe, peixinho é.",
    meaning: "The apple doesn't fall far from the tree.",
  },
];

module.exports = proverbs;
